Various Improvements
KinsonDigital/GitHubData pull request #34
Opened 2022-08-09 15:25 UTC by CalvinWilkinson

<h1 style="font-weight:bold" align="center">Preview Feature Pull Request</h1>
<h2 style="font-weight:bold" align="center">✅Code Review Checklist✅</h2>

- [ ] The **_head(source)_** branch for this pull request is a **_preview feature_** branch, with the correct naming syntax, in the following example:
  - A **_head(source)_** branch is the branch being merged into a target branch.
    <details closed><summary>Example</summary>

      ``` xml
      Syntax: preview/feature/<issue-num>-<description>
      Example: preview/feature/123-my-preview-feature
      ```
    </details>

- [ ] The **_head(source)_** branch for this pull request is created from a **_preview release_** branch, with the correct naming syntax, in the following example:
  <details closed><summary>Example</summary>

    ``` xml
    Syntax: preview/v<major>.<minor>.<patch>-preview.<prev-num>
    Example: preview/v1.2.3-preview.4
    ```
  </details>

- [ ] The **_base(target)_** branch for this pull request is a **_preview release_** branch, with the correct naming syntax, in the following example:
  - A **_base(target)_** branch is the branch that the **_head(source)_** branch is merging into.

    <details closed><summary>Example</summary>

      ``` xml
      Syntax: preview/v<major>.<minor>.<patch>-preview.<prev-num>
      Example: preview/v1.2.3-preview.4
      ```
    </details>

💡For more information on branching, refer to the project's [branching documentation](../../Documentation/Branching.md).

- [ ] Associated issue exists and is linked to this pull request.
  - One issue per pull request.

- [ ] Pull request title matches the title of the associated issue.

- [ ] A ![preview-label](https://user-images.githubusercontent.com/85414302/150838564-33f6044b-55f9-4dd9-8783-1d739de9d92f.png) label has been added to the pull request.

- [ ] The labels attached to this PR match the labels attached to the associated issue.

- [ ] My code follows the coding style of this project.
  - The style is enforced by the **_.editorconfig_** files in the project and displayed as warnings.  If there is an edge case, reach out and let's discuss it.

- [ ] I have manually tested my code changes to the best of my ability.

- [ ] All tests passed locally.
  - This is required because unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
  - Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
  - Status checks run for this pull request when merging into the **_preview/v\*.\*.\*-preview.\*_** branch.  These status checks run every time a change is pushed to the pull request.  These checks validate version syntax, tagging, builds, unit tests, and more.

2022-08-12 17:37 UTC, KinsonDigitalAdmin requested changes

2022-08-12 17:37 UTC, KinsonDigitalAdmin commented on GitHubData/Exceptions/RateLimitException.cs
> +// TODO: Create tests
Remove TODO item

2022-08-12 17:37 UTC, KinsonDigitalAdmin commented on GitHubData/Exceptions/RateLimitException.cs
> +/// Occurs the GitHub request rate limit has been reached.
Refactor code docs to below:

```suggestion
/// Occurs when the GitHub request rate limit has been reached.
```

2022-08-12 17:37 UTC, KinsonDigitalAdmin commented on GitHubData/Factories/HTTPClientFactory.cs
> +/// Creates an <see cref="IHttpClient"/> for making HTTP request.
Refactor code docs to below:

```suggestion
/// Creates an <see cref="IHttpClient"/> for making HTTP requests.
```

2022-08-12 17:37 UTC, KinsonDigitalAdmin commented on GitHubData/Factories/HTTPClientFactory.cs
> +    public static IHttpClient CreateHTTPClient(bool useAsSingleton = false)
Refactor name of argument to `createAsSingleton`

```suggestion
    public static IHttpClient CreateHTTPClient(bool createAsSingleton = false)
```

2022-08-12 17:37 UTC, KinsonDigitalAdmin commented on GitHubData/Models/CoreModel.cs
> +/// or unauthorized request.
Refactor code docs to below:

```suggestion
/// Core information about the rate limits of an authorized or unauthorized request.
```

2022-08-12 17:37 UTC, KinsonDigitalAdmin commented on GitHubData/Models/ResourcesModel.cs
> +/// an authorized or unauthorized account.
Refactor code docs to below:

```suggestion
/// Holds information about the rate limits of an authorized or unauthorized request.
```

2022-08-12 17:37 UTC, KinsonDigitalAdmin commented on GitHubData/Models/ResourcesModel.cs
> +    /// Gets or sets the core limit info.
Refactor to below:

```suggestion
    /// Gets or sets the core data.
```

2022-08-12 17:37 UTC, KinsonDigitalAdmin commented on GitHubData/ResourcesModelJSONConverter.cs
> +/// Converts a JSON to a <see cref="ResourcesModel"/> object.
Refactor code docs to below:

```suggestion
/// Converts JSON data to a <see cref="ResourcesModel"/> object.
```

2022-08-12 17:37 UTC, KinsonDigitalAdmin commented on GitHubData/Services/IGitHubDataService.cs
> +    /// Gets or sets the auth token to use when making requests for GitHub data.
Refactor code docs to below:

```suggestion
    /// Gets or sets the authorization token to use when making requests for GitHub data.
```

2022-08-12 17:37 UTC, KinsonDigitalAdmin commented on GitHubData/Services/IGitHubDataService.cs
> +    /// <remarks>If the token is null or empty, then non-authorized requests will be made.</remarks>
Refactor code docs to below:

```suggestion
    /// <remarks>If the token is null or empty, then non-authorized requests will be used.</remarks>
```

2022-08-12 17:37 UTC, KinsonDigitalAdmin commented on GitHubData/Services/IRequestRateLimitService.cs
> +    /// Gets or sets the auth token to use when making requests for GitHub data.
Refactor code docs to below:

```suggestion
    /// Gets or sets the authorization token to use when making requests for GitHub data.
```

2022-08-12 17:37 UTC, KinsonDigitalAdmin commented on GitHubData/Services/IRequestRateLimitService.cs
> +    /// <remarks>If the token is null or empty, then non-authorized requests will be made.</remarks>
Refactor code docs to below:

```suggestion
    /// <remarks>If the token is null or empty, then non-authorized requests will be used.</remarks>
```

2022-08-12 17:45 UTC, KinsonDigitalAdmin approved these changes

2022-08-13 08:29 UTC, kselena requested changes

2022-08-13 08:29 UTC, kselena commented on GitHubData/Models/ResourcesModel.cs
> +/// Holds various resources information about the rate limits of an authorized or unauthorized account.
Grammar
```suggestion
/// Holds various resources' information about the rate limits of an authorized or unauthorized account.
```

2022-08-13 08:29 UTC, kselena commented on GitHubData/RateLimit.cs
> +    /// Gets or sets the remaining requests available that is allowed
Grammar
```suggestion
    /// Gets or sets the remaining requests available that are allowed
```

2022-08-13 08:29 UTC, kselena commented on GitHubData/ResourcesModelJSONConverter.cs
> +    /// Read and convert the JSON to <see cref="ResourcesModel"/>.
Grammar
```suggestion
    /// Reads and converts the JSON to <see cref="ResourcesModel"/>.
```

2022-08-13 08:29 UTC, kselena commented on GitHubData/ResourcesModelJSONConverter.cs
> +    /// A converter may throw any Exception, but should throw <cref>JsonException</cref> when the JSON is invalid.
Grammar
```suggestion
    /// A converter may throw any exception but should throw <cref>JsonException</cref> when the JSON is invalid.
```

2022-08-13 08:29 UTC, kselena commented on GitHubData/ResourcesModelJSONConverter.cs
> +    /// <param name="reader">The <see cref="Utf8JsonReader"/> to read from.</param>
Grammar
```suggestion
    /// <param name="reader">The <see cref="Utf8JsonReader"/> to read.</param>
```

2022-08-13 08:29 UTC, kselena commented on GitHubData/ResourcesModelJSONConverter.cs
> +    /// A converter may throw any Exception, but should throw <cref>JsonException</cref> when the JSON
Grammar
```suggestion
    /// A converter may throw any exception but should throw <cref>JsonException</cref> when the JSON
```

2022-08-13 08:29 UTC, kselena commented on GitHubData/ResourcesModelJSONConverter.cs
> +    /// <param name="writer">The <see cref="Utf8JsonWriter"/> to write to.</param>
Grammar
```suggestion
    /// <param name="writer">The <see cref="Utf8JsonWriter"/> to write.</param>
```

2022-08-13 09:01 UTC, kselena approved these changes

2022-08-13 09:45 UTC, merged